- name: Create pci-sim device profile for tempest run
  hosts: "{{ cifmw_target_hook_host | default('localhost') }}"
  gather_facts: false
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  tasks:
    - name: Create Python venv in openstackclient pod
      ansible.builtin.shell: |
        oc -n {{ namespace }} exec pod/openstackclient -- python3 -m venv /tmp/venv

    - name: Install OpenStack and Cyborg clients
      ansible.builtin.shell: |
        oc -n {{ namespace }} exec pod/openstackclient -- \
          /tmp/venv/bin/pip install python-openstackclient python-cyborgclient

    - name: Create pci-sim device profile for cyborg tempest plugin tests
      ansible.builtin.shell: |
        oc -n {{ namespace }} exec pod/openstackclient -- \
          /tmp/venv/bin/openstack --insecure accelerator device profile create pci-sim-cyborg-dp \
          '[{"resources:CUSTOM_PCI":"1","trait:CUSTOM_PCI_PRODUCT_ID_1000":"required"}]'
