apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openstack
# TODO: add generation of tempest test specification and run_tempest.sh script.
# currently we are just running the minimal set of tempest tests using the
# run_tempest.sh script from the tempest container. To be able to control the
# concurrency of the tests we need to generate a replacement script which can
# be injected into the container via a configmap. The is also needed to enable
# us to do a two phase run where we run the api tests in parallel and then run the
# scenario tests serially. as is done in the integrated-compute job.
# https://github.com/openstack/tempest/blob/master/tox.ini#L201-L214
resources:
- tempest.yaml
