linters:
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - errorlint
    - revive
    - ginkgolinter
    - gofmt
    - govet
    - gosec
    - errname
    - err113
run:
  timeout: 5m
