---
- job:
    name: nova-operator-kuttl
    parent: cifmw-multinode-kuttl-operator-target
    dependencies: ["openstack-meta-content-provider"]
    roles:
      - zuul: github.com/openstack-k8s-operators/ci-framework
    description: |
      This job deploy a basic "Compute Starter Kit" topology
      https://www.openstack.org/software/sample-configs#compute-starter-kit
      that is the minimum set of openstack services required to boot a vm.
    post-run:
      - ci/nova-operator-base/playbooks/collect-logs.yaml
    vars:
      collection_namespace_override: "nova-kuttl-default"
      operator_name: nova-operator
      nova_repo: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/nova-operator"
      zuul_log_collection: true
      nova_hook: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/openstack-k8s-operators/nova-operator'].src_dir }}/ci/nova-operator-kuttl/deploy_webhooks.yaml"
      pre_kuttl_from_operator:
        - name: 70 Create nova webhooks
          type: playbook
          source: "{{ nova_hook }}"
          extra_vars:
            nova_catalog_image: "{{ content_provider_registry_ip }}:5001/openstack-k8s-operators/nova-operator-index:{{ zuul.patchset }}"
    extra-vars:
      crc_ci_bootstrap_networking:
        networks:
          default:
            range: 192.168.122.0/24
            mtu: 1500
          internal-api:
            vlan: 20
            range: 172.17.0.0/24
          storage:
            vlan: 21
            range: 172.18.0.0/24
          tenant:
            vlan: 22
            range: 172.19.0.0/24
        instances:
          controller:
            networks:
              default:
                ip: 192.168.122.11
          crc:
            networks:
              default:
                ip: 192.168.122.10
              internal-api:
                ip: 172.17.0.5
              storage:
                ip: 172.18.0.5
              tenant:
                ip: 172.19.0.5
- job:
    name: nova-operator-tempest-multinode
    parent: podified-multinode-edpm-deployment-crc-3comp
    dependencies: ["openstack-meta-content-provider"]
    nodeset: centos-9-medium-3x-centos-9-crc-extracted-2-39-0-3xl
    post-run:
      - ci/nova-operator-base/playbooks/collect-logs.yaml
    vars:
      cifmw_extras:
        - "@scenarios/centos-9/multinode-ci.yml"
        - "@{{ ansible_user_dir }}/{{ zuul.projects['github.com/openstack-k8s-operators/nova-operator'].src_dir }}/ci/nova-operator-tempest-multinode/ci_fw_vars.yaml"
      cifmw_run_test_role: test_operator
      cifmw_test_operator_tempest_concurrency: 4
      cifmw_test_operator_timeout: 7200
      cifmw_test_operator_tempest_network_attachments:
        - ctlplane
      # avoid using default test_operator exclude list
      cifmw_test_operator_tempest_tests_exclude_override_scenario: false
      # NOTE(gibi): identity.v3_endpoint_type override is a WA to force the
      # publicURL as otherwise tempest gets configured with adminURL and that
      # causes test instability.
      # NOTE(efoley): swift and cinder are not disabled, we're just telling
      # tempest that they're unavailable so that it'll skip the tests that
      # require cinder or swift
      # TODO(sean-k-mooney): we are currently using cirros 0.5.2 we should be using 0.6.2
      # for now we need to use the old password cubswin:) but we should update this to gocubsgo!
      # once we update the image
      cifmw_test_operator_tempest_tempestconf_config:
          overrides: |
            identity.v3_endpoint_type public
            compute-feature-enabled.vnc_console true
            compute-feature-enabled.stable_rescue true
            compute-feature-enabled.hostname_fqdn_sanitization true
            compute-feature-enabled.live_migration true
            compute-feature-enabled.live_migrate_back_and_forth true
            compute-feature-enabled.block_migration_for_live_migration true
            compute-feature-enabled.ide_bus false
            service_available.swift false
            service_available.cinder false
            validation.image_ssh_user cirros
            validation.image_ssh_password cubswin:)
            validation.image_alt_ssh_user cirros
            validation.image_alt_ssh_password cubswin:)
            validation.allowed_network_downtime 10
      cifmw_test_operator_tempest_include_list: |
          tempest.api.compute
          tempest.scenario
      # ide tests cannot be used with our default machine type.
      # test_live_block_migration_paused is currently blocked by
      # https://issues.redhat.com/browse/RHEL-33754
      cifmw_test_operator_tempest_exclude_list: |
          test_live_block_migration_paused
      # We need to use a custom cpu model to allow live migrating between
      # slightly different computes coming from the node pool
      cifmw_edpm_deploy_nova_compute_extra_config: |
        [libvirt]
        cpu_mode = custom
        cpu_models = Nehalem
- job:
    name: nova-operator-tempest-multinode-ceph
    parent: podified-multinode-hci-deployment-crc-3comp
    dependencies: ["openstack-meta-content-provider"]
    nodeset: centos-9-medium-3x-centos-9-crc-extracted-2-39-0-3xl
    # Note:  When inheriting from a job (or creating a variant of a job) vars are merged with previous definitions
    post-run:
      - ci/nova-operator-base/playbooks/collect-logs.yaml
    vars:
      cifmw_extras:
        - "@scenarios/centos-9/multinode-ci.yml"
        - "@{{ ansible_user_dir }}/{{ zuul.projects['github.com/openstack-k8s-operators/nova-operator'].src_dir }}/ci/nova-operator-tempest-multinode-ceph/ci_fw_vars.yaml"
      # dedupe this later
      cifmw_run_test_role: test_operator
      cifmw_test_operator_tempest_concurrency: 4
      cifmw_test_operator_timeout: 7200
      cifmw_test_operator_tempest_network_attachments:
        - ctlplane
      # NOTE(gibi): identity.v3_endpoint_type override is a WA to force the
      # publicURL as otherwise tempest gets configured with adminURL and that
      # causes test instability.
      # TODO(sean-k-mooney): we are currently using cirros 0.5.2 we should be using 0.6.2
      # for now we need to use the old password cubswin:) but we should update this to gocubsgo!
      # once we update the image
      cifmw_test_operator_tempest_tempestconf_config:
          overrides: |
            identity.v3_endpoint_type public
            compute-feature-enabled.vnc_console true
            compute-feature-enabled.stable_rescue true
            compute-feature-enabled.hostname_fqdn_sanitization true
            compute-feature-enabled.live_migration true
            compute-feature-enabled.live_migrate_back_and_forth true
            compute-feature-enabled.block_migration_for_live_migration false
            compute-feature-enabled.ide_bus false
            compute-feature-enabled.volume_backed_live_migration true
            compute-feature-enabled.volume_multiattach true
            volume.volume_type_multiattach multiattach
            volume.storage_protocol ceph
            service_available.swift false
            service_available.cinder true
            validation.image_ssh_user cirros
            validation.image_ssh_password cubswin:)
            validation.image_alt_ssh_user cirros
            validation.image_alt_ssh_password cubswin:)
            validation.allowed_network_downtime 10
      cifmw_test_operator_tempest_include_list: |
          tempest.api.compute
          tempest.scenario
      # ide tests cannot be used with our default machine type.
      # test_server_detach_rules and test_old_versions_reject are blocked by the requirement
      # to use service tokens to authenticate with cinder when a volume is attached to a server
      # as such the tests are not valid following CVE-2023-2088
      # test_encrypted_cinder_volumes_cryptsetup use encryption format plain which is either
      # not supported by ceph or a volume type that supports it is not available.
      # luks support is enabled and we are testing encrypted volumes with luks.
      # tempest.scenario.test_network_v6 is disabled as it is 8 slow test case
      # that does not cover nova functionality. Also we keep running it in
      # the non ceph job.
      cifmw_test_operator_tempest_exclude_list: |
          tempest.scenario.test_server_volume_attachment.TestServerVolumeAttachmentScenario.test_server_detach_rules
          tempest.scenario.test_server_volume_attachment.TestServerVolumeAttachScenarioOldVersion.test_old_versions_reject
          tempest.scenario.test_encrypted_cinder_volumes.TestEncryptedCinderVolumes.test_encrypted_cinder_volumes_cryptsetup
          tempest.scenario.test_network_v6
      # We need to use a custom cpu model to allow live migrating between
      # slightly different computes coming from the node pool
      # for ceph i might need to add https://github.com/openstack-k8s-operators/docs/blob/main/ceph.md#configure-nova
      # but if i do i can just add that here as i dont know what the fsid will be
      cifmw_edpm_deploy_nova_compute_extra_config: |
        [libvirt]
        cpu_mode = custom
        cpu_models = Nehalem

- project:
    name: openstack-k8s-operators/nova-operator
    default-branch: main
    merge-mode: rebase
    github-check:
      jobs:
        - openstack-meta-content-provider:
            vars:
              cifmw_install_yamls_sdk_version: v1.41.1
        - nova-operator-kuttl
        - nova-operator-tempest-multinode
        - nova-operator-tempest-multinode-ceph

- pragma:
    implied-branch-matchers: True
    implied-branches:
      - main
      - master

##########################################################
#                                                        #
#               Project Template                         #
#                                                        #
##########################################################

- project-template:
    name: opendev-nova-edpm-pipeline
    # Project template to run meta content provider and
    # EDPM job with master opendev and github operator content in
    # openstack-experimental pipeline.
    openstack-experimental: &experimentalJobs
      jobs:
        - openstack-meta-content-provider:
            override-checkout: main
            # when run from nova we need to ensure we list the nova-operator
            # so that it will be built by the meta content provider
            required-projects:
              - github.com/openstack-k8s-operators/nova-operator
            vars:
              cifmw_bop_openstack_release: master
              cifmw_bop_dlrn_baseurl: "https://trunk.rdoproject.org/centos9-master"
              cifmw_repo_setup_branch: master
              cifmw_install_yamls_sdk_version: v1.41.1
        - nova-operator-tempest-multinode: &job_vars
            override-checkout: main
            # when run from nova we need to ensure we list the nova-operator
            # so that it will be built by the meta content provider
            required-projects:
              - github.com/openstack-k8s-operators/nova-operator
            vars:
              cifmw_repo_setup_branch: master
        - nova-operator-tempest-multinode-ceph: *job_vars
    experimental: *experimentalJobs
