---
- name: Tempest
  hosts: "{{ target_host | default('controller') }}"
  vars:
    nova_operator_basedir: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/nova-operator"
  tasks:
    - name: Use OpenStack Namespace
      ansible.builtin.command: oc project openstack
      changed_when: false

    - name: Deploy OpenStack
      ansible.builtin.command: "oc apply -k {{ nova_operator_basedir }}/ci/nova-operator-compute-kit/topology/tempest"
      changed_when: true

    - name: Wait for tempest-worker pod to start
      ansible.builtin.command: oc wait pod tempest-worker --for condition=Ready --timeout=120s
      changed_when: false

    - name: Create local tempest log dir
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/zuul-output/logs/controller/tempest"
        state: directory
        mode: "0755"

    - name: Run tempest tests
      ansible.builtin.command: "oc rsh pod/tempest-worker /var/lib/tempest/run_tempest.sh"
      register: tempest_output
      changed_when: true

    - name: Save tempest output
      ansible.builtin.copy:
        dest: "{{ ansible_user_dir }}/zuul-output/logs/controller/tempest/tempest-output.txt"
        content: "{{ tempest_output.stdout }}"
        mode: "0644"

    # TODO(sean-k-mooney): copy the html test report to the zuul output dir.
