apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  ironic:
    enabled: false
    template:
      ironicConductors: []
  manila:
    enabled: false
    template:
      manilaShares: {}
  horizon:
    enabled: false
