# permissions for end users to view novaapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novaapi-viewer-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - novaapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novaapis/status
  verbs:
  - get
