# permissions for end users to view nova.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nova-viewer-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - nova
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - nova/status
  verbs:
  - get
