# permissions for end users to edit placementapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: placementapi-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nova-operator
    app.kubernetes.io/part-of: nova-operator
    app.kubernetes.io/managed-by: kustomize
  name: placementapi-editor-role
rules:
- apiGroups:
  - placement.openstack.org
  resources:
  - placementapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - placement.openstack.org
  resources:
  - placementapis/status
  verbs:
  - get
