apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operatorframework.io/suggested-namespace: openstack
    operators.operatorframework.io/operator-type: non-standalone
  name: nova-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NovaAPI is the Schema for the novaapis API
      displayName: Nova API
      kind: NovaAPI
      name: novaapis.nova.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: tls
      version: v1beta1
    - description: NovaCell is the Schema for the novacells API
      displayName: Nova Cell
      kind: NovaCell
      name: novacells.nova.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: metadataServiceTemplate.tls
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: noVNCProxyServiceTemplate.tls
      - description: Service - Cert secret used for the nova novnc service endpoint
        displayName: Service
        path: noVNCProxyServiceTemplate.tls.service
      - description: Vencrypt - cert secret containing the x509 certificate to be
          presented to the VNC server. The CommonName field should match the primary
          hostname of the controller node. If using a HA deployment, the Organization
          field can also be configured to a value that is common across all console
          proxy instances in the deployment. https://docs.openstack.org/nova/latest/admin/remote-console-access.html#novnc-proxy-server-configuration
        displayName: Vencrypt
        path: noVNCProxyServiceTemplate.tls.vencrypt
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: tls
      version: v1beta1
    - description: NovaCompute is the Schema for the NovaCompute
      displayName: Nova Compute
      kind: NovaCompute
      name: novacomputes.nova.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: tls
      version: v1beta1
    - description: NovaConductor is the Schema for the novaconductors API
      displayName: Nova Conductor
      kind: NovaConductor
      name: novaconductors.nova.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: tls
      version: v1beta1
    - description: NovaMetadata is the Schema for the novametadata API
      displayName: Nova Metadata
      kind: NovaMetadata
      name: novametadata.nova.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: tls
      version: v1beta1
    - description: NovaNoVNCProxy is the Schema for the novanovncproxies API
      displayName: Nova No VNCProxy
      kind: NovaNoVNCProxy
      name: novanovncproxies.nova.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: tls
      - description: Service - Cert secret used for the nova novnc service endpoint
        displayName: Service
        path: tls.service
      - description: Vencrypt - cert secret containing the x509 certificate to be
          presented to the VNC server. The CommonName field should match the primary
          hostname of the controller node. If using a HA deployment, the Organization
          field can also be configured to a value that is common across all console
          proxy instances in the deployment. https://docs.openstack.org/nova/latest/admin/remote-console-access.html#novnc-proxy-server-configuration
        displayName: Vencrypt
        path: tls.vencrypt
      version: v1beta1
    - description: Nova is the Schema for the nova API
      displayName: Nova
      kind: Nova
      name: novas.nova.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: apiServiceTemplate.tls
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: cellTemplates.metadataServiceTemplate.tls
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: cellTemplates.noVNCProxyServiceTemplate.tls
      - description: Service - Cert secret used for the nova novnc service endpoint
        displayName: Service
        path: cellTemplates.noVNCProxyServiceTemplate.tls.service
      - description: Vencrypt - cert secret containing the x509 certificate to be
          presented to the VNC server. The CommonName field should match the primary
          hostname of the controller node. If using a HA deployment, the Organization
          field can also be configured to a value that is common across all console
          proxy instances in the deployment. https://docs.openstack.org/nova/latest/admin/remote-console-access.html#novnc-proxy-server-configuration
        displayName: Vencrypt
        path: cellTemplates.noVNCProxyServiceTemplate.tls.vencrypt
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: metadataServiceTemplate.tls
      version: v1beta1
    - description: NovaScheduler is the Schema for the novaschedulers API
      displayName: Nova Scheduler
      kind: NovaScheduler
      name: novaschedulers.nova.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: tls
      version: v1beta1
    - description: PlacementAPI is the Schema for the placementapis API
      displayName: Placement API
      kind: PlacementAPI
      name: placementapis.placement.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: tls
      version: v1beta1
  description: Nova Operator
  displayName: Nova Operator
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - OpenStack
  - Nova
  links:
  - name: Nova Operator
    url: https://github.com/openstack-k8s-operators/nova-operator
  maturity: beta
  provider:
    name: Red Hat Inc.
    url: https://redhat.com/
  version: 0.0.0
