//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	topologyv1beta1 "github.com/openstack-k8s-operators/infra-operator/apis/topology/v1beta1"
	"github.com/openstack-k8s-operators/lib-common/modules/common/condition"
	"github.com/openstack-k8s-operators/lib-common/modules/common/service"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIOverrideSpec) DeepCopyInto(out *APIOverrideSpec) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = make(map[service.Endpoint]service.RoutedOverrideSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIOverrideSpec.
func (in *APIOverrideSpec) DeepCopy() *APIOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(APIOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSpec.
func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cyborg) DeepCopyInto(out *Cyborg) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cyborg.
func (in *Cyborg) DeepCopy() *Cyborg {
	if in == nil {
		return nil
	}
	out := new(Cyborg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cyborg) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyborgAPI) DeepCopyInto(out *CyborgAPI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyborgAPI.
func (in *CyborgAPI) DeepCopy() *CyborgAPI {
	if in == nil {
		return nil
	}
	out := new(CyborgAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CyborgAPI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyborgAPIList) DeepCopyInto(out *CyborgAPIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CyborgAPI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyborgAPIList.
func (in *CyborgAPIList) DeepCopy() *CyborgAPIList {
	if in == nil {
		return nil
	}
	out := new(CyborgAPIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CyborgAPIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyborgAPISpec) DeepCopyInto(out *CyborgAPISpec) {
	*out = *in
	in.CyborgAPITemplate.DeepCopyInto(&out.CyborgAPITemplate)
	if in.ConfigSecret != nil {
		in, out := &in.ConfigSecret, &out.ConfigSecret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyborgAPISpec.
func (in *CyborgAPISpec) DeepCopy() *CyborgAPISpec {
	if in == nil {
		return nil
	}
	out := new(CyborgAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyborgAPIStatus) DeepCopyInto(out *CyborgAPIStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyborgAPIStatus.
func (in *CyborgAPIStatus) DeepCopy() *CyborgAPIStatus {
	if in == nil {
		return nil
	}
	out := new(CyborgAPIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyborgAPITemplate) DeepCopyInto(out *CyborgAPITemplate) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.Override.DeepCopyInto(&out.Override)
	in.TLS.DeepCopyInto(&out.TLS)
	if in.TopologyRef != nil {
		in, out := &in.TopologyRef, &out.TopologyRef
		*out = new(topologyv1beta1.TopoRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyborgAPITemplate.
func (in *CyborgAPITemplate) DeepCopy() *CyborgAPITemplate {
	if in == nil {
		return nil
	}
	out := new(CyborgAPITemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyborgConductor) DeepCopyInto(out *CyborgConductor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyborgConductor.
func (in *CyborgConductor) DeepCopy() *CyborgConductor {
	if in == nil {
		return nil
	}
	out := new(CyborgConductor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CyborgConductor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyborgConductorList) DeepCopyInto(out *CyborgConductorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CyborgConductor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyborgConductorList.
func (in *CyborgConductorList) DeepCopy() *CyborgConductorList {
	if in == nil {
		return nil
	}
	out := new(CyborgConductorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CyborgConductorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyborgConductorSpec) DeepCopyInto(out *CyborgConductorSpec) {
	*out = *in
	in.CyborgConductorTemplate.DeepCopyInto(&out.CyborgConductorTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyborgConductorSpec.
func (in *CyborgConductorSpec) DeepCopy() *CyborgConductorSpec {
	if in == nil {
		return nil
	}
	out := new(CyborgConductorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyborgConductorStatus) DeepCopyInto(out *CyborgConductorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyborgConductorStatus.
func (in *CyborgConductorStatus) DeepCopy() *CyborgConductorStatus {
	if in == nil {
		return nil
	}
	out := new(CyborgConductorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyborgConductorTemplate) DeepCopyInto(out *CyborgConductorTemplate) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.TopologyRef != nil {
		in, out := &in.TopologyRef, &out.TopologyRef
		*out = new(topologyv1beta1.TopoRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyborgConductorTemplate.
func (in *CyborgConductorTemplate) DeepCopy() *CyborgConductorTemplate {
	if in == nil {
		return nil
	}
	out := new(CyborgConductorTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyborgDefaults) DeepCopyInto(out *CyborgDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyborgDefaults.
func (in *CyborgDefaults) DeepCopy() *CyborgDefaults {
	if in == nil {
		return nil
	}
	out := new(CyborgDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyborgImages) DeepCopyInto(out *CyborgImages) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyborgImages.
func (in *CyborgImages) DeepCopy() *CyborgImages {
	if in == nil {
		return nil
	}
	out := new(CyborgImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyborgList) DeepCopyInto(out *CyborgList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cyborg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyborgList.
func (in *CyborgList) DeepCopy() *CyborgList {
	if in == nil {
		return nil
	}
	out := new(CyborgList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CyborgList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyborgSpec) DeepCopyInto(out *CyborgSpec) {
	*out = *in
	in.CyborgSpecCore.DeepCopyInto(&out.CyborgSpecCore)
	out.CyborgImages = in.CyborgImages
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyborgSpec.
func (in *CyborgSpec) DeepCopy() *CyborgSpec {
	if in == nil {
		return nil
	}
	out := new(CyborgSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyborgSpecCore) DeepCopyInto(out *CyborgSpecCore) {
	*out = *in
	if in.KeystoneInstance != nil {
		in, out := &in.KeystoneInstance, &out.KeystoneInstance
		*out = new(string)
		**out = **in
	}
	if in.DatabaseInstance != nil {
		in, out := &in.DatabaseInstance, &out.DatabaseInstance
		*out = new(string)
		**out = **in
	}
	out.MessagingBus = in.MessagingBus
	if in.ServiceUser != nil {
		in, out := &in.ServiceUser, &out.ServiceUser
		*out = new(string)
		**out = **in
	}
	if in.PasswordSelectors != nil {
		in, out := &in.PasswordSelectors, &out.PasswordSelectors
		*out = new(PasswordSelector)
		**out = **in
	}
	if in.DatabaseAccount != nil {
		in, out := &in.DatabaseAccount, &out.DatabaseAccount
		*out = new(string)
		**out = **in
	}
	if in.APITimeout != nil {
		in, out := &in.APITimeout, &out.APITimeout
		*out = new(int)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(string)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	in.APIServiceTemplate.DeepCopyInto(&out.APIServiceTemplate)
	in.ConductorServiceTemplate.DeepCopyInto(&out.ConductorServiceTemplate)
	if in.TopologyRef != nil {
		in, out := &in.TopologyRef, &out.TopologyRef
		*out = new(topologyv1beta1.TopoRef)
		**out = **in
	}
	out.Auth = in.Auth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyborgSpecCore.
func (in *CyborgSpecCore) DeepCopy() *CyborgSpecCore {
	if in == nil {
		return nil
	}
	out := new(CyborgSpecCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyborgStatus) DeepCopyInto(out *CyborgStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyborgStatus.
func (in *CyborgStatus) DeepCopy() *CyborgStatus {
	if in == nil {
		return nil
	}
	out := new(CyborgStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordSelector) DeepCopyInto(out *PasswordSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordSelector.
func (in *PasswordSelector) DeepCopy() *PasswordSelector {
	if in == nil {
		return nil
	}
	out := new(PasswordSelector)
	in.DeepCopyInto(out)
	return out
}
