apiVersion: cyborg.openstack.org/v1beta1
kind: CyborgAPI
metadata:
  labels:
    app.kubernetes.io/name: nova-operator
    app.kubernetes.io/managed-by: kustomize
  name: cyborgapi-sample
spec:
  configSecret: cyborg-sample-config
