apiVersion: nova.openstack.org/v1beta1
kind: NovaScheduler
metadata:
  name: novascheduler-sample
spec:
  secret: osp-secret
  apiDatabaseHostname: openstack
  cell0DatabaseHostname: openstack
  keystoneAuthURL: http://keystone-public-openstack.apps-crc.testing
  customServiceConfig: |
    [DEFAULT]
    debug=true
  serviceAccount: nova
  registeredCells: {}
