# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: mariadb.openstack.org/v1beta1
kind: MariaDBDatabase
metadata:
  labels:
    dbName: openstack
  name: placement
  namespace: openstack
spec:
  name: placement 
  secret: placement-secret
