---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: compute-1
  gather_facts: false
  tasks:
    - name: ensure expected directories exist
      ansible.builtin.include_tasks: test-helpers/verify_dir.yaml
      with_items:
        # common directories
        - "/etc/tmpfiles.d/"
        - "/var/lib/openstack"
        - "/var/lib/openstack/config/containers"
        - "/var/log/containers"
        - "/var/log/containers/stdouts"
        # extrenal deps
        - "/etc/ceph"
        - "/run/openvswitch"
        # libvirt directories
        - "/var/lib/libvirt"
        - "/var/lib/openstack/config/libvirt"
        - "/var/log/containers/libvirt"
        # nova directories
        - "/var/lib/nova"
        - "/var/lib/openstack/config/nova"
        - "/var/lib/_nova_secontext"
        - "/var/lib/nova/instances"
        - "/var/log/containers/nova"
    - name: ensure firewall is configured
      ansible.builtin.include_tasks: test-helpers/verify_firewall.yaml
    - name: ensure systemd services are defined and functional
      ansible.builtin.include_tasks: test-helpers/verify_systemd_service.yaml
      with_items:
        - "edpm_libvirt_virtlogd"
        - "edpm_libvirt_virtnodedevd"
        - "edpm_libvirt_virtproxyd"
        - "edpm_libvirt_virtqemud"
        - "edpm_libvirt_virtsecretd"
        - "edpm_nova_compute"
    - name: ensure podman container exists and are running
      ansible.builtin.include_tasks: test-helpers/verify_podman.yaml
      with_items:
        - "libvirt_virtlogd"
        - "libvirt_virtnodedevd"
        - "libvirt_virtproxyd"
        - "libvirt_virtqemud"
        - "libvirt_virtsecretd"
        - "nova_compute"
    - name: ensure podman container volume mounts
      ansible.builtin.include_tasks: test-helpers/verify_podman_volumes.yaml
      with_items:
        - { name: "libvirt_virtlogd",
            volumes: "\
            [{bind  /var/lib/openstack/config/libvirt /var/lib/openstack/config   [rbind] false rprivate} \
             {bind  /etc/localtime /etc/localtime   [rbind] false rprivate} \
             {bind  /var/log/containers/libvirt /var/log/containers/libvirt   [rbind] true rprivate} \
             {bind  /var/lib/libvirt /var/lib/libvirt   [rbind] true rprivate} \
             {bind  /var/lib/nova /var/lib/nova   [rbind] true rprivate} \
             {bind  /run/libvirt /run/libvirt   [nosuid nodev rbind] true rprivate}]"
          }
        - { name: "libvirt_virtnodedevd",
            volumes: "\
            [{bind  /dev /dev   [nosuid rbind] true rprivate} \
             {bind  /var/lib/openstack/config/libvirt /var/lib/openstack/config   [rbind] false rprivate} \
             {bind  /etc/localtime /etc/localtime   [rbind] false rprivate} \
             {bind  /var/log/containers/libvirt /var/log/containers/libvirt   [rbind] true rprivate} \
             {bind  /var/lib/libvirt /var/lib/libvirt   [rbind] true rprivate} \
             {bind  /run/libvirt /run/libvirt   [nosuid nodev rbind] true rprivate}]"
          }
        - { name: "libvirt_virtproxyd",
            volumes: "\
            [{bind  /var/log/containers/libvirt /var/log/containers/libvirt   [rbind] true rprivate} \
             {bind  /var/lib/libvirt /var/lib/libvirt   [rbind] true rprivate} \
             {bind  /run/libvirt /run/libvirt   [nosuid nodev rbind] true rprivate} \
             {bind  /var/lib/openstack/config/libvirt /var/lib/openstack/config   [rbind] false rprivate} \
             {bind  /etc/localtime /etc/localtime   [rbind] false rprivate}]"
          }
        - { name: "libvirt_virtqemud",
            volumes: "\
            [{bind  /var/lib/libvirt /var/lib/libvirt   [rbind] true rprivate} \
             {bind  /var/lib/nova /var/lib/nova   [rbind] true rprivate} \
             {bind  /run/libvirt /run/libvirt   [nosuid nodev rbind] true rprivate} \
             {bind  /dev /dev   [nosuid rbind] true rprivate} \
             {bind  /etc/ceph /var/lib/openstack/config/ceph   [rbind] false rprivate} \
             {bind  /var/lib/openstack/config/libvirt /var/lib/openstack/config   [rbind] false rprivate} \
             {bind  /etc/localtime /etc/localtime   [rbind] false rprivate} \
             {bind  /var/log/containers/libvirt /var/log/containers/libvirt   [rbind] true rprivate}]"
          }
        - { name: "libvirt_virtsecretd",
            volumes: "\
            [{bind  /etc/localtime /etc/localtime   [rbind] false rprivate} \
             {bind  /var/log/containers/libvirt /var/log/containers/libvirt   [rbind] true rprivate} \
             {bind  /var/lib/libvirt /var/lib/libvirt   [rbind] true rprivate} \
             {bind  /run/libvirt /run/libvirt   [nosuid nodev rbind] true rprivate} \
             {bind  /var/lib/openstack/config/libvirt /var/lib/openstack/config   [rbind] false rprivate}]"
          }
        - { name: "nova_compute",
            volumes: "\
            [{bind  /run/openvswitch /run/openvswitch   [nosuid nodev rbind] true rprivate} \
             {bind  /etc/localtime /etc/localtime   [rbind] false rprivate} \
             {bind  /var/lib/libvirt /var/lib/libvirt   [rbind] true rprivate} \
             {bind  /lib/modules /lib/modules   [rbind] false rprivate} \
             {bind  /var/log/containers/nova /var/log/containers/nova   [rbind] true rprivate} \
             {bind  /var/lib/openstack/config/nova /var/lib/openstack/config/   [rbind] false rprivate} \
             {bind  /run/libvirt /run/libvirt   [nosuid nodev rbind] true rprivate} \
             {bind  /etc/ceph /var/lib/openstack/config/ceph   [rbind] false rprivate} \
             {bind  /dev /dev   [nosuid rbind] true rprivate} {bind  /var/lib/nova /var/lib/nova/   [rbind] true rprivate}]"
          }
