ServerTokens Prod
ServerSignature Off
TraceEnable Off

ServerName "cyborg.openstack.svc"
ServerRoot "/etc/httpd"

PidFile run/httpd.pid
Timeout 90
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 15
LimitRequestFieldSize 8190
LimitRequestFields 100

User apache
Group apache
Listen {{ .APIPublicPort }}

AccessFileName .htaccess
<FilesMatch "^\.ht">
    Require all denied
</FilesMatch>

<Directory />
    Options FollowSymLinks
    AllowOverride None
</Directory>

HostnameLookups Off
EnableSendfile On

TypesConfig /etc/mime.types
Include "/etc/httpd/conf.modules.d/*.conf"
Include "/etc/httpd/conf.d/*.conf"

LogFormat "%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%a %l %u %t \"%r\" %>s %b" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent
LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %s %b \"%{Referer}i\" \"%{User-agent}i\"" forwarded

ErrorLog /dev/stderr
TransferLog /dev/stdout
CustomLog /dev/stdout combined env=!forwarded
CustomLog /dev/stdout proxy env=!forwarded
LogLevel info
