---
- name: Kustomize ControlPlane
  hosts: "{{ cifmw_target_hook_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Ensure the kustomizations dir exists
      ansible.builtin.file:
        path: "{{ cifmw_basedir }}/artifacts/manifests/kustomizations/controlplane"
        state: directory

    - name: Create kustomization
      ansible.builtin.copy:
        dest: "{{ cifmw_basedir }}/artifacts/manifests/kustomizations/controlplane/71-controlplane-kustomization.yaml"
        content: |-
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          resources:
          namespace: {{ cifmw_install_yamls_defaults['NAMESPACE'] }}
          patches:
          - target:
              kind: OpenStackControlPlane
            patch: |-
              - op: replace
                path: /spec/nova/template/apiServiceTemplate/replicas
                value: 2

              - op: replace
                path: /spec/nova/template/notificationsBusInstance
                value: rabbitmq

              - op: replace
                path: /spec/neutron/template/replicas
                value: 2

              - op: replace
                path: /spec/neutron/template/customServiceConfig
                value: |
                  [DEFAULT]
                  debug = True

              - op: replace
                path: /spec/keystone/template/replicas
                value: 2

              - op: add
                path: /spec/nova/template/cellTemplates
                value:
                  cell0:
                    cellDatabaseAccount: nova-cell0
                    hasAPIAccess: true
                    metadataServiceTemplate:
                      enabled: false
                  cell1:
                    cellDatabaseAccount: nova-cell1
                    hasAPIAccess: true
                    cellMessageBusInstance: rabbitmq-cell1
                    cellDatabaseInstance: openstack-cell1
                    metadataServiceTemplate:
                      enabled: true
                      override:
                        service:
                          metadata:
                            annotations:
                              metallb.universe.tf/address-pool: internalapi
                              metallb.universe.tf/allow-shared-ip: internalapi
                              metallb.universe.tf/loadBalancerIPs: 172.17.0.80
                          spec:
                            type: LoadBalancer

              - op: add
                path: /spec/nova/template/metadataServiceTemplate/enabled
                value: false
