/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group nova --version v1beta1 --kind NovaAPI --programmatic-validation --defaulting
//

package v1beta1

import (
	"fmt"

	"github.com/google/go-cmp/cmp"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/util/validation/field"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"

	"github.com/openstack-k8s-operators/lib-common/modules/common/service"
	topologyv1 "github.com/openstack-k8s-operators/infra-operator/apis/topology/v1beta1"
)

// NovaAPIDefaults -
type NovaAPIDefaults struct {
	ContainerImageURL string
}

var novaAPIDefaults NovaAPIDefaults

// log is for logging in this package.
var novaapilog = logf.Log.WithName("novaapi-resource")

// SetupNovaAPIDefaults - initialize NovaAPI spec defaults for use with either internal or external webhooks
func SetupNovaAPIDefaults(defaults NovaAPIDefaults) {
	novaAPIDefaults = defaults
	novaapilog.Info("NovaAPI defaults initialized", "defaults", defaults)
}

// SetupWebhookWithManager sets up the webhook with the Manager
func (r *NovaAPI) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		Complete()
}

//+kubebuilder:webhook:path=/mutate-nova-openstack-org-v1beta1-novaapi,mutating=true,failurePolicy=fail,sideEffects=None,groups=nova.openstack.org,resources=novaapis,verbs=create;update,versions=v1beta1,name=mnovaapi.kb.io,admissionReviewVersions=v1

var _ webhook.Defaulter = &NovaAPI{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *NovaAPI) Default() {
	novaapilog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this NovaAPI spec
func (spec *NovaAPISpec) Default() {
	if spec.ContainerImage == "" {
		spec.ContainerImage = novaAPIDefaults.ContainerImageURL
	}
}

// TODO(user): change verbs to "verbs=create;update;delete" if you want to enable deletion validation.
//+kubebuilder:webhook:path=/validate-nova-openstack-org-v1beta1-novaapi,mutating=false,failurePolicy=fail,sideEffects=None,groups=nova.openstack.org,resources=novaapis,verbs=create;update,versions=v1beta1,name=vnovaapi.kb.io,admissionReviewVersions=v1

var _ webhook.Validator = &NovaAPI{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *NovaAPI) ValidateCreate() (admission.Warnings, error) {
	novaapilog.Info("validate create", "name", r.Name)

	errors := field.ErrorList{}
	basePath := field.NewPath("spec")

	// validate the service override key is valid
	errors = append(errors, service.ValidateRoutedOverrides(basePath.Child("override").Child("service"), r.Spec.Override.Service)...)

	errors = append(errors,
		ValidateAPIDefaultConfigOverwrite(
			basePath.Child("defaultConfigOverwrite"),
			r.Spec.DefaultConfigOverwrite)...)

	if r.Spec.TopologyRef != nil {
		if err := topologyv1.ValidateTopologyNamespace(r.Spec.TopologyRef.Namespace, *basePath, r.Namespace); err != nil {
			errors = append(errors, err)
		}
	}

	if len(errors) != 0 {
		novaapilog.Info("validation failed", "name", r.Name)
		return nil, apierrors.NewInvalid(
			schema.GroupKind{Group: "nova.openstack.org", Kind: "NovaAPI"},
			r.Name, errors)
	}
	return nil, nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *NovaAPI) ValidateUpdate(old runtime.Object) (admission.Warnings, error) {
	novaapilog.Info("validate update", "name", r.Name)
	oldNovaAPI, ok := old.(*NovaAPI)
	if !ok || oldNovaAPI == nil {
		return nil, apierrors.NewInternalError(fmt.Errorf("unable to convert existing object"))
	}

	novaapilog.Info("validate update", "diff", cmp.Diff(oldNovaAPI, r))

	errors := field.ErrorList{}
	basePath := field.NewPath("spec")

	// validate the service override key is valid
	errors = append(errors, service.ValidateRoutedOverrides(basePath.Child("override").Child("service"), r.Spec.Override.Service)...)

	errors = append(errors,
		ValidateAPIDefaultConfigOverwrite(
			basePath.Child("defaultConfigOverwrite"),
			r.Spec.DefaultConfigOverwrite)...)

	if r.Spec.TopologyRef != nil {
		if err := topologyv1.ValidateTopologyNamespace(r.Spec.TopologyRef.Namespace, *basePath, r.Namespace); err != nil {
			errors = append(errors, err)
		}
	}

	if len(errors) != 0 {
		novaapilog.Info("validation failed", "name", r.Name)
		return nil, apierrors.NewInvalid(
			schema.GroupKind{Group: "nova.openstack.org", Kind: "NovaAPI"},
			r.Name, errors)
	}
	return nil, nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *NovaAPI) ValidateDelete() (admission.Warnings, error) {
	novaapilog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil, nil
}

func ValidateAPIDefaultConfigOverwrite(
	basePath *field.Path,
	defaultConfigOverwrite map[string]string,
) field.ErrorList {
	return ValidateDefaultConfigOverwrite(
		basePath,
		defaultConfigOverwrite,
		[]string{"policy.yaml", "api-paste.ini"})
}

// Validate validates the referenced TopoRef.Namespace.
func (r *NovaAPITemplate) ValidateAPITopology(
	basePath *field.Path,
	namespace string,
) *field.Error {
	if err := topologyv1.ValidateTopologyNamespace(
		r.TopologyRef.Namespace, *basePath, namespace); err != nil {
		return err
	}
	return nil
}
