/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group nova --version v1beta1 --kind NovaNoVNCProxy --programmatic-validation --defaulting
//

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/validation/field"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

// NovaNoVNCProxyDefaults -
type NovaNoVNCProxyDefaults struct {
	ContainerImageURL string
}

var novaNoVNCProxyDefaults NovaNoVNCProxyDefaults

// log is for logging in this package.
var novanovncproxylog = logf.Log.WithName("novanovncproxy-resource")

// SetupNovaNoVNCProxyDefaults - initialize NovaNoVNCProxy spec defaults for use with either internal or external webhooks
func SetupNovaNoVNCProxyDefaults(defaults NovaNoVNCProxyDefaults) {
	novaNoVNCProxyDefaults = defaults
	novanovncproxylog.Info("NovaNoVNCProxy defaults initialized", "defaults", defaults)
}

// SetupWebhookWithManager sets up the webhook with the Manager
func (r *NovaNoVNCProxy) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		Complete()
}

//+kubebuilder:webhook:path=/mutate-nova-openstack-org-v1beta1-novanovncproxy,mutating=true,failurePolicy=fail,sideEffects=None,groups=nova.openstack.org,resources=novanovncproxies,verbs=create;update,versions=v1beta1,name=mnovanovncproxy.kb.io,admissionReviewVersions=v1

var _ webhook.Defaulter = &NovaNoVNCProxy{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *NovaNoVNCProxy) Default() {
	novanovncproxylog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this NovaNoVNCProxy spec
func (spec *NovaNoVNCProxySpec) Default() {
	if spec.ContainerImage == "" {
		spec.ContainerImage = novaNoVNCProxyDefaults.ContainerImageURL
	}
}

// TODO(user): change verbs to "verbs=create;update;delete" if you want to enable deletion validation.
//+kubebuilder:webhook:path=/validate-nova-openstack-org-v1beta1-novanovncproxy,mutating=false,failurePolicy=fail,sideEffects=None,groups=nova.openstack.org,resources=novanovncproxies,verbs=create;update,versions=v1beta1,name=vnovanovncproxy.kb.io,admissionReviewVersions=v1

var _ webhook.Validator = &NovaNoVNCProxy{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *NovaNoVNCProxy) ValidateCreate() (admission.Warnings, error) {
	novanovncproxylog.Info("validate create", "name", r.Name)

	// TODO(user): fill in your validation logic upon object creation.
	return nil, nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *NovaNoVNCProxy) ValidateUpdate(old runtime.Object) (admission.Warnings, error) {
	novanovncproxylog.Info("validate update", "name", r.Name)

	// TODO(user): fill in your validation logic upon object update.
	return nil, nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *NovaNoVNCProxy) ValidateDelete() (admission.Warnings, error) {
	novanovncproxylog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil, nil
}

// ValidateCell0 validates cell0 NoVNCProxy template. This is expected to be
// called by higher level validation webhooks
func (r *NovaNoVNCProxyTemplate) ValidateCell0(basePath *field.Path) field.ErrorList {
	var errors field.ErrorList
	if *r.Enabled {
		errors = append(
			errors,
			field.Invalid(
				basePath.Child("enabled"), *r.Enabled, "should be false for cell0"),
		)
	}
	return errors
}

// called by higher level validation webhooks
func (r *NovaNoVNCProxyTemplateCore) ValidateCell0(basePath *field.Path) field.ErrorList {
	var errors field.ErrorList
	if *r.Enabled {
		errors = append(
			errors,
			field.Invalid(
				basePath.Child("enabled"), *r.Enabled, "should be false for cell0"),
		)
	}
	return errors
}
