/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group nova --version v1beta1 --kind NovaExternalCompute --programmatic-validation --defaulting
//

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
)

// NovaExternalComputeDefaults -
type NovaExternalComputeDefaults struct {
	ComputeContainerImageURL   string
	LibvirtContainerImageURL   string
	AnsibleEEContainerImageURL string
}

var novaExternalComputeDefaults NovaExternalComputeDefaults

// log is for logging in this package.
var novaexternalcomputelog = logf.Log.WithName("novaexternalcompute-resource")

// SetupNovaExternalComputeDefaults - initialize NovaExternalCompute spec defaults for use with either internal or external webhooks
func SetupNovaExternalComputeDefaults(defaults NovaExternalComputeDefaults) {
	novaExternalComputeDefaults = defaults
	novalog.Info("NovaExternalCompute defaults initialized", "defaults", defaults)
}

// SetupWebhookWithManager sets up the webhook with the Manager
func (r *NovaExternalCompute) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		Complete()
}

//+kubebuilder:webhook:path=/mutate-nova-openstack-org-v1beta1-novaexternalcompute,mutating=true,failurePolicy=fail,sideEffects=None,groups=nova.openstack.org,resources=novaexternalcomputes,verbs=create;update,versions=v1beta1,name=mnovaexternalcompute.kb.io,admissionReviewVersions=v1

var _ webhook.Defaulter = &NovaExternalCompute{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *NovaExternalCompute) Default() {
	novaexternalcomputelog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this NovaExternalCompute spec
func (spec *NovaExternalComputeSpec) Default() {
	if spec.AnsibleEEContainerImage == "" {
		spec.AnsibleEEContainerImage = novaExternalComputeDefaults.AnsibleEEContainerImageURL
	}

	if spec.NovaComputeContainerImage == "" {
		spec.NovaComputeContainerImage = novaExternalComputeDefaults.ComputeContainerImageURL
	}

	if spec.NovaLibvirtContainerImage == "" {
		spec.NovaLibvirtContainerImage = novaExternalComputeDefaults.LibvirtContainerImageURL
	}
}

// NOTE: change verbs to "verbs=create;update;delete" if you want to enable deletion validation.
//+kubebuilder:webhook:path=/validate-nova-openstack-org-v1beta1-novaexternalcompute,mutating=false,failurePolicy=fail,sideEffects=None,groups=nova.openstack.org,resources=novaexternalcomputes,verbs=create;update,versions=v1beta1,name=vnovaexternalcompute.kb.io,admissionReviewVersions=v1

var _ webhook.Validator = &NovaExternalCompute{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *NovaExternalCompute) ValidateCreate() error {
	novaexternalcomputelog.Info("validate create", "name", r.Name)

	// TODO(user): fill in your validation logic upon object creation.
	return nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *NovaExternalCompute) ValidateUpdate(old runtime.Object) error {
	novaexternalcomputelog.Info("validate update", "name", r.Name)

	// TODO(user): fill in your validation logic upon object update.
	return nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *NovaExternalCompute) ValidateDelete() error {
	novaexternalcomputelog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil
}
