/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group nova --version v1beta1 --kind NovaComputeIronic --programmatic-validation --defaulting
//

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
)

// NovaComputeIronicDefaults -
type NovaComputeIronicDefaults struct {
	ContainerImageURL string
}

var novaComputeIronicDefaults NovaComputeIronicDefaults

// log is for logging in this package.
var novacomputeironiclog = logf.Log.WithName("novacomputeironic-resource")

// SetupNovaComputeIronicDefaults - initialize NovaComputeIronic spec defaults for use with either internal or external webhooks
func SetupNovaComputeIronicDefaults(defaults NovaComputeIronicDefaults) {
	novaComputeIronicDefaults = defaults
	novacomputeironiclog.Info("NovaComputeIronic defaults initialized", "defaults", defaults)
}

// SetupWebhookWithManager sets up the webhook with the Manager
func (r *NovaComputeIronic) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		Complete()
}

//+kubebuilder:webhook:path=/mutate-nova-openstack-org-v1beta1-novacomputeironic,mutating=true,failurePolicy=fail,sideEffects=None,groups=nova.openstack.org,resources=novacomputeironics,verbs=create;update,versions=v1beta1,name=mnovacomputeironic.kb.io,admissionReviewVersions=v1

var _ webhook.Defaulter = &NovaComputeIronic{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *NovaComputeIronic) Default() {
	novacomputeironiclog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this novacomputeironic spec
func (spec *NovaComputeIronicSpec) Default() {
	if spec.ContainerImage == "" {
		spec.ContainerImage = novaComputeIronicDefaults.ContainerImageURL
	}
}

// TODO(user): change verbs to "verbs=create;update;delete" if you want to enable deletion validation.
//+kubebuilder:webhook:path=/validate-nova-openstack-org-v1beta1-novacomputeironic,mutating=false,failurePolicy=fail,sideEffects=None,groups=nova.openstack.org,resources=novacomputeironics,verbs=create;update,versions=v1beta1,name=vnovacomputeironic.kb.io,admissionReviewVersions=v1

var _ webhook.Validator = &NovaComputeIronic{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *NovaComputeIronic) ValidateCreate() error {
	novacomputeironiclog.Info("validate create", "name", r.Name)

	// TODO(user): fill in your validation logic upon object creation.
	return nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *NovaComputeIronic) ValidateUpdate(old runtime.Object) error {
	novacomputeironiclog.Info("validate update", "name", r.Name)

	// TODO(user): fill in your validation logic upon object update.
	return nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *NovaComputeIronic) ValidateDelete() error {
	novacomputeironiclog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil
}
