/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1beta1

import (
	topologyv1 "github.com/openstack-k8s-operators/infra-operator/apis/topology/v1beta1"
	condition "github.com/openstack-k8s-operators/lib-common/modules/common/condition"
	"github.com/openstack-k8s-operators/lib-common/modules/common/tls"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.

// NovaConductorTemplate defines the input parameters specified by the user to
// create a NovaConductor via higher level CRDs.
type NovaConductorTemplate struct {
	// +kubebuilder:validation:Optional
	// +kubebuilder:default=1
	// +kubebuilder:validation:Maximum=32
	// +kubebuilder:validation:Minimum=0
	// Replicas of the service to run
	Replicas *int32 `json:"replicas"`

	// +kubebuilder:validation:Optional
	// NodeSelector to target subset of worker nodes running this service. Setting here overrides
	// any global NodeSelector settings within the Nova CR.
	NodeSelector *map[string]string `json:"nodeSelector,omitempty"`

	// +kubebuilder:validation:Optional
	// CustomServiceConfig - customize the service config using this parameter to change service defaults,
	// or overwrite rendered information using raw OpenStack config format. The content gets added to
	// to /etc/<service>/<service>.conf.d directory as custom.conf file.
	CustomServiceConfig string `json:"customServiceConfig"`

	// +kubebuilder:validation:Optional
	// Resources - Compute Resources required by this service (Limits/Requests).
	// https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
	Resources corev1.ResourceRequirements `json:"resources,omitempty"`

	// +kubebuilder:validation:Optional
	// NetworkAttachments is a list of NetworkAttachment resource names to expose the services to the given network
	NetworkAttachments []string `json:"networkAttachments,omitempty"`

	// +kubebuilder:validation:Optional
	// TopologyRef to apply the Topology defined by the associated CR referenced
	// by name
	TopologyRef *topologyv1.TopoRef `json:"topologyRef,omitempty"`
}

// NovaConductorSpec defines the desired state of NovaConductor
type NovaConductorSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// +kubebuilder:validation:Required
	// CellName is the name of the Nova Cell this conductor belongs to.
	CellName string `json:"cellName"`

	// +kubebuilder:validation:Required
	// Secret is the name of the Secret instance containing password
	// information for the nova-conductor service. This secret is expected to
	// be generated by the nova-operator based on the information passed to the
	// Nova CR.
	Secret string `json:"secret"`

	// +kubebuilder:validation:Optional
	// +kubebuilder:default=nova
	// ServiceUser - optional username used for this service to register in
	// keystone
	ServiceUser string `json:"serviceUser"`

	// +kubebuilder:validation:Required
	// KeystoneAuthURL - the URL that the nova-conductor service can use to
	// talk to keystone
	KeystoneAuthURL string `json:"keystoneAuthURL"`

	// +kubebuilder:validation:Optional
	// +kubebuilder:default=regionOne
	// Region - the region name to use for service endpoint discovery
	Region string `json:"region"`

	// +kubebuilder:validation:Optional
	// +kubebuilder:default=nova
	// APIDatabaseAccount - MariaDBAccount to use when accessing the API DB
	APIDatabaseAccount string `json:"apiDatabaseAccount"`

	// +kubebuilder:validation:Optional
	// APIDatabaseHostname - hostname to use when accessing the API DB. If not
	// provided then up-calls will be disabled. This filed is Required for
	// cell0.
	// TODO(gibi): Add a webhook to validate cell0 constraint
	APIDatabaseHostname string `json:"apiDatabaseHostname"`

	// +kubebuilder:validation:Optional
	// +kubebuilder:default=nova
	// CellDatabaseAccount - MariaDBAccount to use when accessing the cell DB
	CellDatabaseAccount string `json:"cellDatabaseAccount"`

	// +kubebuilder:validation:Optional
	// NOTE(gibi): This should be Required, see notes in KeystoneAuthURL
	// CellDatabaseHostname - hostname to use when accessing the cell DB
	CellDatabaseHostname string `json:"cellDatabaseHostname"`

	// +kubebuilder:validation:Optional
	// +kubebuilder:default=false
	// PreserveJobs - do not delete jobs after they finished e.g. to check logs
	PreserveJobs bool `json:"preserveJobs"`

	// NovaServiceBase specifies the generic fields of the service
	NovaServiceBase `json:",inline"`

	// +kubebuilder:validation:Required
	// ServiceAccount - service account name used internally to provide Nova services the default SA name
	ServiceAccount string `json:"serviceAccount"`

	// +kubebuilder:validation:Optional
	// +operator-sdk:csv:customresourcedefinitions:type=spec
	// TLS - Parameters related to the TLS
	TLS tls.Ca `json:"tls,omitempty"`

	// +kubebuilder:validation:Required
	// MemcachedInstance is the name of the Memcached CR that all nova service will use.
	MemcachedInstance string `json:"memcachedInstance"`

	// +kubebuilder:validation:Optional
	// DBPurge defines the parameters for the DB archiving and purging cron job
	DBPurge NovaCellDBPurge `json:"dbPurge"`
}

// NovaConductorStatus defines the observed state of NovaConductor
type NovaConductorStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// Map of hashes to track e.g. job status
	Hash map[string]string `json:"hash,omitempty"`

	// Conditions
	Conditions condition.Conditions `json:"conditions,omitempty" optional:"true"`

	// ReadyCount defines the number of replicas ready from nova-conductor
	ReadyCount int32 `json:"readyCount,omitempty"`

	// NetworkAttachments status of the deployment pods
	NetworkAttachments map[string][]string `json:"networkAttachments,omitempty"`

	// ObservedGeneration - the most recent generation observed for this
	// service. If the observed generation is less than the spec generation,
	// then the controller has not processed the latest changes injected by
	// the openstack-operator in the top-level CR (e.g. the ContainerImage)
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// LastAppliedTopology - the last applied Topology
	LastAppliedTopology *topologyv1.TopoRef `json:"lastAppliedTopology,omitempty"`
}

//+kubebuilder:object:root=true
//+kubebuilder:subresource:status
//+kubebuilder:printcolumn:name="NetworkAttachments",type="string",JSONPath=".spec.networkAttachments",description="NetworkAttachments"
//+kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.conditions[0].status",description="Status"
//+kubebuilder:printcolumn:name="Message",type="string",JSONPath=".status.conditions[0].message",description="Message"

// NovaConductor is the Schema for the novaconductors API
type NovaConductor struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NovaConductorSpec   `json:"spec,omitempty"`
	Status NovaConductorStatus `json:"status,omitempty"`
}

//+kubebuilder:object:root=true

// NovaConductorList contains a list of NovaConductor
type NovaConductorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NovaConductor `json:"items"`
}

func init() {
	SchemeBuilder.Register(&NovaConductor{}, &NovaConductorList{})
}

// GetConditions returns the list of conditions from the status
func (s NovaConductorStatus) GetConditions() condition.Conditions {
	return s.Conditions
}

// NewNovaConductorSpec constructs a NovaConductorSpec
func NewNovaConductorSpec(
	novaCell NovaCellSpec,
) NovaConductorSpec {
	conductorSpec := NovaConductorSpec{
		CellName:             novaCell.CellName,
		Secret:               novaCell.Secret,
		CellDatabaseHostname: novaCell.CellDatabaseHostname,
		CellDatabaseAccount:  novaCell.CellDatabaseAccount,
		APIDatabaseHostname:  novaCell.APIDatabaseHostname,
		APIDatabaseAccount:   novaCell.APIDatabaseAccount,
		NovaServiceBase: NovaServiceBase{
			ContainerImage:      novaCell.ConductorContainerImageURL,
			Replicas:            novaCell.ConductorServiceTemplate.Replicas,
			NodeSelector:        novaCell.ConductorServiceTemplate.NodeSelector,
			TopologyRef:         novaCell.ConductorServiceTemplate.TopologyRef,
			CustomServiceConfig: novaCell.ConductorServiceTemplate.CustomServiceConfig,
			Resources:           novaCell.ConductorServiceTemplate.Resources,
			NetworkAttachments:  novaCell.ConductorServiceTemplate.NetworkAttachments,
		},
		KeystoneAuthURL:   novaCell.KeystoneAuthURL,
		ServiceUser:       novaCell.ServiceUser,
		Region:            novaCell.Region,
		ServiceAccount:    novaCell.ServiceAccount,
		TLS:               novaCell.TLS,
		PreserveJobs:      novaCell.PreserveJobs,
		MemcachedInstance: novaCell.MemcachedInstance,
		DBPurge:           novaCell.DBPurge,
	}

	if conductorSpec.NodeSelector == nil {
		conductorSpec.NodeSelector = novaCell.NodeSelector
	}

	if conductorSpec.TopologyRef == nil {
		conductorSpec.TopologyRef = novaCell.TopologyRef
	}

	return conductorSpec
}

// GetSecret returns the value of the NovaConductor.Spec.Secret
func (n NovaConductor) GetSecret() string {
	return n.Spec.Secret
}

// GetKeystoneAuthURL returns the KeystoneAuthURL from the Spec
func (n NovaConductor) GetKeystoneAuthURL() string {
	return n.Spec.KeystoneAuthURL
}

// GetKeystoneUser returns the Service user from the Spec
func (n NovaConductor) GetKeystoneUser() string {
	return n.Spec.ServiceUser
}

// GetCABundleSecretName returns the TLS CA bundle name from the Spec
func (n NovaConductor) GetCABundleSecretName() string {
	return n.Spec.TLS.CaBundleSecretName
}

// GetRegion returns the Region from the Spec
func (n NovaConductor) GetRegion() string {
	return n.Spec.Region
}

// GetSpecTopologyRef - Returns the LastAppliedTopology Set in the Status
func (n *NovaConductor) GetSpecTopologyRef() *topologyv1.TopoRef {
	return n.Spec.TopologyRef
}

// GetLastAppliedTopology - Returns the LastAppliedTopology Set in the Status
func (n *NovaConductor) GetLastAppliedTopology() *topologyv1.TopoRef {
	return n.Status.LastAppliedTopology
}

// SetLastAppliedTopology - Sets the LastAppliedTopology value in the Status
func (n *NovaConductor) SetLastAppliedTopology(topologyRef *topologyv1.TopoRef) {
	n.Status.LastAppliedTopology = topologyRef
}
