/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group nova --version v1beta1 --kind NovaCell --programmatic-validation --defaulting
//

package v1beta1

import (
	"fmt"
	"regexp"

	"github.com/google/go-cmp/cmp"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/util/validation/field"
	"k8s.io/utils/ptr"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
	topologyv1 "github.com/openstack-k8s-operators/infra-operator/apis/topology/v1beta1"
)

// CRDNameRegex is the regex pattern for validating CRD names
const CRDNameRegex = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$"

// NovaCellDefaults -
type NovaCellDefaults struct {
	ConductorContainerImageURL   string
	MetadataContainerImageURL    string
	NoVNCContainerImageURL       string
	NovaComputeContainerImageURL string
}

var novaCellDefaults NovaCellDefaults

// log is for logging in this package.
var novacelllog = logf.Log.WithName("novacell-resource")

// SetupNovaCellDefaults - initialize NovaCell spec defaults for use with either internal or external webhooks
func SetupNovaCellDefaults(defaults NovaCellDefaults) {
	novaCellDefaults = defaults
	novacelllog.Info("NovaCell defaults initialized", "defaults", defaults)
}

var _ webhook.Defaulter = &NovaCell{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *NovaCell) Default() {
	novacelllog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this NovaCell spec
func (spec *NovaCellSpec) Default() {
	spec.NovaCellImages.Default(novaCellDefaults)

	if spec.MetadataServiceTemplate.Enabled == nil {
		spec.MetadataServiceTemplate.Enabled = ptr.To(false)
	}

	if spec.CellName == Cell0Name {
		// in cell0 disable VNC by default
		if spec.NoVNCProxyServiceTemplate.Enabled == nil {
			spec.NoVNCProxyServiceTemplate.Enabled = ptr.To(false)
		}
	} else {
		// in other cells enable VNC  by default
		if spec.NoVNCProxyServiceTemplate.Enabled == nil {
			spec.NoVNCProxyServiceTemplate.Enabled = ptr.To(true)
		}
	}
}

var _ webhook.Validator = &NovaCell{}

func (spec *NovaCellSpec) validate(basePath *field.Path, namespace string) field.ErrorList {
	var errors field.ErrorList

	if spec.CellName == Cell0Name {
		errors = append(
			errors, spec.MetadataServiceTemplate.ValidateCell0(
				basePath.Child("metadataServiceTemplate"))...,
		)
		errors = append(
			errors, spec.NoVNCProxyServiceTemplate.ValidateCell0(
				basePath.Child("noVNCProxyServiceTemplate"))...,
		)
		errors = append(
			errors,
			ValidateNovaComputeCell0(
				basePath.Child("novaComputeTemplates"), len(spec.NovaComputeTemplates))...)
	}

	// validate topology if passed to the CellSpec (regardless of CellName).
	// because a NovaCell CR can be created independently, TopologyRef should
	// be validated for the underlying components (metadata, conductor,
	// novncproxy, compute templates).
	errors = append(errors, topologyv1.ValidateTopologyRef(
		spec.TopologyRef, *basePath.Child("topologyRef"), namespace)...)

	errors = append(errors,
		spec.MetadataServiceTemplate.ValidateTopology(
			basePath.Child("metadataServiceTemplate"),
			namespace)...)

	errors = append(errors,
		spec.NoVNCProxyServiceTemplate.ValidateTopology(
			basePath.Child("noVNCProxyServiceTemplate"),
			namespace)...)

	errors = append(errors,
		spec.ConductorServiceTemplate.ValidateTopology(
			basePath.Child("conductorServiceTemplate"),
			namespace)...)

	for computeName, computeTemplate := range spec.NovaComputeTemplates {
		if computeTemplate.ComputeDriver == IronicDriver {
			errors = append(
				errors, computeTemplate.ValidateIronicDriverReplicas(
					basePath.Child("novaComputeTemplates").Key(computeName))...,
			)
		}
		errors = append(
			errors, ValidateNovaComputeName(
				basePath.Child("novaComputeTemplates").Key(computeName), computeName)...,
		)
		errors = append(
			errors, computeTemplate.ValidateDefaultConfigOverwrite(
				basePath.Child("novaComputeTemplates").Key(computeName))...,
		)

		errors = append(
			errors, computeTemplate.ValidateTopology(
				basePath.Child("novaComputeTemplates").Key(computeName), namespace)...,
		)
	}

	errors = append(
		errors, ValidateCellName(
			basePath.Child("cellName"), spec.CellName)...,
	)
	errors = append(
		errors,
		spec.DBPurge.Validate(basePath.Child("dbPurge"))...,
	)

	return errors
}

// ValidateCreate validates the NovaCellSpec during the webhook invocation
func (spec *NovaCellSpec) ValidateCreate(basePath *field.Path, namespace string) field.ErrorList {
	return spec.validate(basePath, namespace)
}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *NovaCell) ValidateCreate() (admission.Warnings, error) {
	novacelllog.Info("validate create", "name", r.Name)
	errors := field.ErrorList{}
	basePath := field.NewPath("spec")

	errors = r.Spec.ValidateCreate(basePath, r.Namespace)

	if len(errors) != 0 {
		novacelllog.Info("validation failed", "name", r.Name)
		return nil, apierrors.NewInvalid(
			schema.GroupKind{Group: "nova.openstack.org", Kind: "NovaCell"},
			r.Name, errors)
	}
	return nil, nil
}

// ValidateUpdate validates the NovaCellSpec during the webhook invocation
func (spec *NovaCellSpec) ValidateUpdate(old NovaCellSpec, basePath *field.Path, namespace string) field.ErrorList {
	return spec.validate(basePath, namespace)
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *NovaCell) ValidateUpdate(old runtime.Object) (admission.Warnings, error) {
	novacelllog.Info("validate update", "name", r.Name)
	errors := field.ErrorList{}
	basePath := field.NewPath("spec")

	oldCell, ok := old.(*NovaCell)
	if !ok || oldCell == nil {
		return nil, apierrors.NewInternalError(fmt.Errorf("unable to convert existing object"))
	}

	novacelllog.Info("validate update", "diff", cmp.Diff(oldCell, r))

	errors = r.Spec.ValidateUpdate(oldCell.Spec, basePath, r.Namespace)

	if len(errors) != 0 {
		novacelllog.Info("validation failed", "name", r.Name)
		return nil, apierrors.NewInvalid(
			schema.GroupKind{Group: "nova.openstack.org", Kind: "NovaCell"},
			r.Name, errors)
	}
	return nil, nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *NovaCell) ValidateDelete() (admission.Warnings, error) {
	novacelllog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil, nil
}

// ValidateCellName validates the cell name. It is expected to be called
// from various webhooks.
func ValidateCellName(path *field.Path, cellName string) field.ErrorList {
	var errors field.ErrorList
	if len(cellName) > 35 {
		errors = append(
			errors,
			field.Invalid(
				path, cellName, "should be shorter than 36 characters"),
		)
	}
	match, _ := regexp.MatchString(CRDNameRegex, cellName)
	if !match {
		errors = append(
			errors,
			field.Invalid(
				path, cellName,
				fmt.Sprintf("should match with the regex '%s'", CRDNameRegex)),
		)
	}
	return errors
}
