[DEFAULT]
state_path = /var/lib/
debug = True
{{ if (index . "TransportURL") }}
transport_url = {{ .TransportURL }}
{{ end }}
{{ if (index . "LogFile") }}
log_file = {{ .LogFile }}
{{ end }}

[database]
connection = {{ .DatabaseConnection }}

{{ if (index . "TransportURL") }}
[oslo_messaging_rabbit]
{{- if (index . "QuorumQueues") }}
rabbit_quorum_queue=true
rabbit_transient_quorum_queue=true
amqp_durable_queues=true
{{- else }}
amqp_durable_queues=false
amqp_auto_delete=false
heartbeat_in_pthread=false
{{- end }}
{{ if (index . "CaFilePath") }}
ssl_ca_file = {{ .CaFilePath }}
{{ end }}
{{ end }}

{{ if (index . "KeystoneAuthURL") }}
[keystone_authtoken]
{{ if (index . "ACID") }}
auth_type = v3applicationcredential
application_credential_id = {{ .ACID }}
application_credential_secret = {{ .ACSecret }}
{{ else }}
project_domain_name = Default
project_name = service
user_domain_name = Default
password = {{ .ServicePassword }}
username = {{ .ServiceUser }}
auth_type = password
{{ end }}
auth_url = {{ .KeystoneAuthURL }}
interface = internal
{{ if (index . "Region") }}region_name = {{ index . "Region" }}{{ end }}
{{ if (index . "CaFilePath") }}
cafile = {{ .CaFilePath }}
{{ end }}

[placement]
{{ if (index . "ACID") }}
auth_type = v3applicationcredential
application_credential_id = {{ .ACID }}
application_credential_secret = {{ .ACSecret }}
{{ else }}
project_domain_name = Default
project_name = service
user_domain_name = Default
password = {{ .ServicePassword }}
username = {{ .ServiceUser }}
auth_type = password
{{ end }}
auth_url = {{ .KeystoneAuthURL }}
interface = internal
{{ if (index . "CaFilePath") }}
cafile = {{ .CaFilePath }}
{{ end }}

[nova]
{{ if (index . "ACID") }}
auth_type = v3applicationcredential
application_credential_id = {{ .ACID }}
application_credential_secret = {{ .ACSecret }}
{{ else }}
project_domain_name = Default
project_name = service
user_domain_name = Default
password = {{ .ServicePassword }}
username = {{ .ServiceUser }}
auth_type = password
{{ end }}
auth_url = {{ .KeystoneAuthURL }}
interface = internal
{{ if (index . "CaFilePath") }}
cafile = {{ .CaFilePath }}
{{ end }}

[agent]
enabled_drivers = fake_driver
{{ end }}
