/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group nova --version v1beta1 --kind NovaCompute --programmatic-validation --defaulting
//

package v1beta1

import (
	"fmt"
	"regexp"

	"github.com/google/go-cmp/cmp"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/util/validation/field"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
	topologyv1 "github.com/openstack-k8s-operators/infra-operator/apis/topology/v1beta1"
)

// NovaComputeDefaults -
type NovaComputeDefaults struct {
	ContainerImageURL string
}

var novaComputeDefaults NovaComputeDefaults

// log is for logging in this package.
var novacomputelog = logf.Log.WithName("novacompute-resource")

// SetupNovaComputeDefaults - initialize NovaCompute spec defaults for use with either internal or external webhooks
func SetupNovaComputeDefaults(defaults NovaComputeDefaults) {
	novaComputeDefaults = defaults
	novacomputelog.Info("NovaCompute defaults initialized", "defaults", defaults)
}

var _ webhook.Defaulter = &NovaCompute{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *NovaCompute) Default() {
	novacomputelog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this novacompute spec
func (spec *NovaComputeSpec) Default() {
	if spec.ContainerImage == "" {
		spec.ContainerImage = novaComputeDefaults.ContainerImageURL
	}
}

var _ webhook.Validator = &NovaCompute{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *NovaCompute) ValidateCreate() (admission.Warnings, error) {
	novacomputelog.Info("validate create", "name", r.Name)

	errors := r.Spec.ValidateCreate(field.NewPath("spec"), r.Namespace)

	if len(errors) != 0 {
		novacomputelog.Info("validation failed", "name", r.Name)
		return nil, apierrors.NewInvalid(
			schema.GroupKind{Group: "nova.openstack.org", Kind: "NovaCompute"},
			r.Name, errors)
	}
	return nil, nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *NovaCompute) ValidateUpdate(old runtime.Object) (admission.Warnings, error) {
	novacomputelog.Info("validate update", "name", r.Name)
	oldNovaCompute, ok := old.(*NovaCompute)
	if !ok || oldNovaCompute == nil {
		return nil, apierrors.NewInternalError(fmt.Errorf("unable to convert existing object"))
	}

	novacomputelog.Info("validate update", "diff", cmp.Diff(oldNovaCompute, r))

	errors := r.Spec.ValidateUpdate(oldNovaCompute.Spec, field.NewPath("spec"), r.Namespace)

	if len(errors) != 0 {
		novacomputelog.Info("validation failed", "name", r.Name)
		return nil, apierrors.NewInvalid(
			schema.GroupKind{Group: "nova.openstack.org", Kind: "NovaCompute"},
			r.Name, errors)
	}

	return nil, nil
}

// ValidateCreate validates the NovaComputeSpec during the webhook invocation
func (spec *NovaComputeSpec) ValidateCreate(basePath *field.Path, namespace string) field.ErrorList {
	return spec.validate(basePath, namespace)
}

// ValidateUpdate validates the NovaComputeSpec during the webhook invocation
func (spec *NovaComputeSpec) ValidateUpdate(old NovaComputeSpec, basePath *field.Path, namespace string) field.ErrorList {
	return spec.validate(basePath, namespace)
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *NovaCompute) ValidateDelete() (admission.Warnings, error) {
	novacomputelog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil, nil
}

func (spec *NovaComputeSpec) validate(basePath *field.Path, namespace string) field.ErrorList {
	var errors field.ErrorList

	if spec.ComputeDriver == IronicDriver && *spec.NovaServiceBase.Replicas > 1 {
		errors = append(
			errors,
			field.Invalid(
				basePath.Child("replicas"), *spec.NovaServiceBase.Replicas, "should be max 1 for ironic.IronicDriver"),
		)
	}
	errors = append(
		errors,
		ValidateComputeDefaultConfigOverwrite(
			basePath.Child("defaultConfigOverwrite"), spec.DefaultConfigOverwrite)...)

	errors = append(errors, topologyv1.ValidateTopologyRef(
		spec.TopologyRef, *basePath.Child("topologyRef"), namespace)...)

	return errors
}

// ValidateIronicDriverReplicas validates replicas depend on compute driver
func (r *NovaComputeTemplate) ValidateIronicDriverReplicas(basePath *field.Path) field.ErrorList {
	var errors field.ErrorList
	if *r.Replicas > 1 {
		errors = append(
			errors,
			field.Invalid(
				basePath.Child("replicas"), *r.Replicas, "should be max 1 for ironic.IronicDriver"),
		)
	}
	return errors
}

// ValidateDefaultConfigOverwrite validates the defaultConfigOverwrite for NovaComputeTemplate
func (r *NovaComputeTemplate) ValidateDefaultConfigOverwrite(basePath *field.Path) field.ErrorList {
	return ValidateComputeDefaultConfigOverwrite(
		basePath.Child("defaultConfigOverwrite"), r.DefaultConfigOverwrite)
}

// ValidateComputeDefaultConfigOverwrite validates the defaultConfigOverwrite for NovaCompute
func ValidateComputeDefaultConfigOverwrite(
	basePath *field.Path,
	defaultConfigOverwrite map[string]string,
) field.ErrorList {
	return ValidateDefaultConfigOverwrite(
		basePath, defaultConfigOverwrite, []string{"provider*.yaml"})
}

// ValidateNovaComputeName validates the compute name. It is expected to be called
// from various webhooks.
func ValidateNovaComputeName(path *field.Path, computeName string) field.ErrorList {
	var errors field.ErrorList
	if len(computeName) > 20 {
		errors = append(
			errors,
			field.Invalid(
				path, computeName, "should be shorter than 20 characters"),
		)
	}
	match, _ := regexp.MatchString(CRDNameRegex, computeName)
	if !match {
		errors = append(
			errors,
			field.Invalid(
				path, computeName,
				fmt.Sprintf("should match with the regex '%s'", CRDNameRegex)),
		)
	}
	return errors
}

// ValidateNovaComputeCell0 validates cell0 NoVNCProxy template. This is expected to be
// called by higher level validation webhooks
func ValidateNovaComputeCell0(basePath *field.Path, mapLength int) field.ErrorList {
	var errors field.ErrorList
	if mapLength > 0 {
		errors = append(
			errors,
			field.Invalid(
				basePath, "novaComputeTemplates", "should have zero elements for cell0"),
		)
	}
	return errors
}


// ValidateTopology validates the referenced TopoRef.Namespace.
func (r *NovaComputeTemplate) ValidateTopology(
	basePath *field.Path,
	namespace string,
) field.ErrorList {
	return topologyv1.ValidateTopologyRef(
		r.TopologyRef,
		*basePath.Child("topologyRef"),
		namespace,
	)
}
