name: Lints

on: [push, pull_request]

jobs:
  check-go-mod-replace-lines:
    name: check for replace lines in go.mod files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - name: check for replace lines in go.mod files
        run: |
          ! egrep --invert-match -e '^replace.*/api => \./api|^replace.*//allow-merging$'  `find . -name 'go.mod'` | egrep -e 'go.mod:replace'
